services:
  - type: web
    name: skystream
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPER_ADMIN_USER
        value: Hussain
      - key: SUPER_ADMIN_PASS
        value: hussain9887
      - key: PYTHON_VERSION
        value: 3.11.0
